name: C/C++ CI

on:
  push:
    branches: [ master,gui ]
  pull_request:
    branches: [ master,gui ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make clean
      run: make clean
